### ISSUE TITLE
API key expired?

### ISSUE THREAD

**Issue by calmsleeper** [vaibhavsingh97/random-word#13]
**Describe the bug**
I was using this package with a discord bot to generate random words and it worked fine up until last Friday. The error it throws points to line #24 in random_word.py which tells me "API key either expired or not working. Please raise issue at..."

**To Reproduce**
2. Call function  '....'
3. See error

**Expected behavior**

**Screenshots**
https://i.imgur.com/aVmmdEx.png

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - Python [3.6.8]

**Additional context**

**Comment by vaibhavsingh97** [comment]
@calmsleeper Thanks for opening the issue. I am looking into it and soon update the package with relevant fix.

**Comment by iamhazel** [comment]
Having the same exact problem. My code worked properly in my one project, but then I copied it over to another and started getting that error.

**Comment by choonkiattay** [comment]
hi @vaibhavsingh97  I also encounter the same problem.

Another issue I found when API error: 
RandomWords class __init__ line 23, returns an error _"TypeError: exceptions must derive from BaseException"_. You may change the line to `raise ValueError("API key either expired or not working. Please raise issue at {}".format(self.issue_url))`

**Comment by calmsleeper** [comment]
@vaibhavsingh97 Thank you for the fix the RandomWord package is pulling dictionary words as of today (3/10/19)

**Comment by vaibhavsingh97** [comment]
@calmsleeper @choonkiattay Please update the package to the latest version. I had included the latest fix.

**Comment by vaibhavsingh97** [comment]
I had released a new version on PyPI (https://pypi.org/project/Random-Word/1.0.5/), this will fix recent issues.
