### ISSUE TITLE
Error: No result found

### ISSUE THREAD

**Issue by MrEdinLaw** [vaibhavsingh97/random-word#16]
**Describe the bug**

> site-packages\random_word\random_word.py", line 58, in get_random_word
>     "Error occured, No result found. If you think this was a mistake than raise issue at {}".format(self.issue_url))
> Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues

**To Reproduce**
```
r = RandomWords()
word = r.get_random_word()
```

**Expected behavior**
Word variable should get a random word assigned.

**Screenshots**
No....

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python 3.6 (64bit)

**Additional context**

**Comment by vaibhavsingh97** [comment]
@MrEdinLaw Please update the package to the latest version. I had included the latest fix.

**Comment by MrEdinLaw** [comment]
Thank you very much, the latest update fixed the problem/bug.

**Comment by atschutz** [comment]
I reinstalled the package just now and I'm still getting this error.

**Comment by vaibhavsingh97** [comment]
@atschutz I just did a reinstall to reproduce the error, but I am getting random words
![image](https://user-images.githubusercontent.com/8705386/56643227-d66b6200-6696-11e9-8ead-83a45d66bc64.png)
Can you please help me in opening new issue with proper steps, and environment  you are facing this issue

**Comment by atschutz** [comment]
Just submitted a new issue. Thanks for the quick reply!

**Comment by FremanZhang** [comment]
The same issue occurs in my APP today suddenly, but it was working well in the past. Is there any usage limit on the number of times ?

```
(wx-env) freman@DEV01:~/project/$ python
Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from random_word import RandomWords
>>> nickname = RandomWords().get_random_word()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/freman/project/wechat/wx-env/lib/python3.6/site-packages/random_word/random_word.py", line 60, in get_random_word
    "Error occured, No result found. If you think this was a mistake than raise issue at {}".format(self.issue_url))
Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues
>>> 
```

**Comment by FremanZhang** [comment]
> The same issue occurs in my APP today suddenly, but it was working well in the past. Is there any usage limit on the number of times ?
> 
> ```
> (wx-env) freman@DEV01:~/project/$ python
> Python 3.6.8 (default, Jan 14 2019, 11:02:34) 
> [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> 
> >>> from random_word import RandomWords
> >>> nickname = RandomWords().get_random_word()
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/freman/project/wechat/wx-env/lib/python3.6/site-packages/random_word/random_word.py", line 60, in get_random_word
>     "Error occured, No result found. If you think this was a mistake than raise issue at {}".format(self.issue_url))
> Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues
> >>> 
> ```
I checked the source code of 'random_word.py' and doubted that maybe this is a network issue regarding  the API url 'https://api.wordnik.com/v4/words.json/randomWord?'
```
        try:
            url += urlencode(payload, quote_via=quote_plus)
        except TypeError:
            url += urlencode(payload)
        response = request_url(url)
        result = response.json()
        if response.status_code == 200:
            return result['word']
        else:
            raise Exception(
                "Error occured, No result found. If you think this was a mistake than raise issue at {}".format(self.issue_url))
```

Then tried to switch by a better network line from China and it works. 
To sum up, the connection stability of the API service is a crucial factor.

**Comment by ChemGuy88** [comment]
> To sum up, the connection stability of the API service is a crucial factor.

This would explain the unpredictability in reproducing the error. Thanks for looking into it.
