### ISSUE TITLE
Error: No result found after .py file containing get_random_word() call is run multiple times

### ISSUE THREAD

**Issue by atschutz** [vaibhavsingh97/random-word#17]
**Describe the bug**
After running a .py file that uses get_random_word() or get_random_words() multiple times (usually around 10 times), Error occurs and will continue to occur if user tries to run the file again. 

**To Reproduce**
1. Create a file named "randomWordTest.py" and fill it with the following:
```
from random_word import RandomWords
r = RandomWords()
r.get_random_word()
```

2. In the command prompt, navigate to the file's location and run "python randomWordTest.py"
A random word should appear.

3.   repeat step 2 multiple times, around 10. Eventually, the following error will occur:
```
Error occurred, No result found. If you think this was a mistake than raise issue at {}".format(self.issue_url))
Exception: Error occurred, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues
```
This error will continue to occur about 95% of the time whenever randomWordTest.py is run. Changing the file and then saving it seems to bring user back to step 1. 

**Expected behavior**
randomWordTest.py should return a random word every time. 

**Environment (please complete the following information):**
 - Windows 10
 - Python 3.7.3

**Additional context**
I'm new to python, so there's a chance I'm doing something incorrectly. 
I seem to have followed all steps for installation and usage of the package correctly, though.

**Comment by vaibhavsingh97** [comment]
@atschutz Thanks for such detailed bug report 👍. I am looking into it, most probably it's an API limit, as right now, it's a free tier. I had asked the same questions on support, will update with the reply.

**Comment by lwyss** [comment]
Sam thing happens to me on Mac os but I am also new to python.

**Comment by Hoohm** [comment]
Got the same issue.

**Comment by Puhalenthi** [comment]
Same thing with me

**Comment by simonm3** [comment]
same

**Comment by kronk87** [comment]
Same

**Comment by crimson-lotus** [comment]
The same error occurred on my Mac

**Comment by pqrollan** [comment]
Still having the error

**Comment by Quexxx** [comment]
same

**Comment by Enderxcthz** [comment]
@vaibhavsingh97 are you still planning on implementing a fix?
A nice way would be to make an exception so the error can be handled, wait for a number of seconds then retry.

**Comment by vaibhavsingh97** [comment]
I had released a new version on PyPI (https://pypi.org/project/Random-Word/1.0.5/), this will fix recent issues.
