### ISSUE TITLE
Hide the API key from public

### ISSUE THREAD

**Issue by vaibhavsingh97** [vaibhavsingh97/random-word#2]
**Describe the bug**
An API key should not be exposed to the public.

**To Reproduce**
Right now I am maintaining `config.py` to use API key, and added to gitignore https://github.com/vaibhavsingh97/random-word/blob/759d68455c9d938e739e006013a37a61aa2a1ffa/.gitignore#L106 

This is the reason Travis CI build is also failing (https://travis-ci.org/vaibhavsingh97/random-word)

**Expected behavior**
There should  be someway we can use API key when the package is run else it's encrypted and have no value to the public

**Additional context**
Adding JWT authentication and we can have API key without exposing to the public

**Comment by vaibhavsingh97** [comment]
@jatin69 You are right, at least we can prevent from exposing who will install the new package. I am looking for alternatives we can hide it anyway. Let's see if anyone has the better solution.

>Simply mention the API service link and steps to create an API in case someone wants to extend the project or use it in their own

Yes, I will add it. As you can request your API key but it takes 7-10 days to get delivered in the mail after your requests for an API key. 😅

**Comment by jatin69** [comment]
We can close this issue now if it's done. 😄

**Comment by vaibhavsingh97** [comment]
Closing since it resolved by https://github.com/vaibhavsingh97/random-word/commit/ce30a78cc0424ea1991795dea6fc0573e2338058
