### ISSUE TITLE
Error Occurred, No result found

### ISSUE THREAD

**Issue by Ragingthunder567** [vaibhavsingh97/random-word#28]
**Description**
Error while using the module with random - word failing to generate a word

**To Reproduce**
from random_word import RandomWords
import time

r = RandomWords()

def word_array(primo):
    word_arr = []
    for x in range (len(primo)):
        word_arr.append(primo[x])

    return word_arr

def gap():
    print("")
    print("")

print("Welcome to Hangman!")
time.sleep(0.5)
print("Ready to play?")
gap()
time.sleep(1)
word = r.get_random_word(minLength = 4, maxLength = 8, hasDictionaryDef = "true")
print(word)

**Expected behavior**
Expected to get a word.

**Environment (please complete the following information):**
 - OS: [Windows]
 - Python [3.7]

**Comment by jasperan** [comment]
Having the same issue. Is it possible that we are making too many HTTP requests and there is an unknown rate limiting that we don't know of?

**Comment by plaffitte** [comment]
Same issue here:

Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues

**Comment by michealjroberts** [comment]
I am receiving the same issue:

```
 File "x/x/x/env/lib/python3.7/site-packages/random_word/random_word.py", line 60, in get_random_word
   "Error occured, No result found. If you think this was a mistake than raise issue at {}".format(self.issue_url))
Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues
```

Using the following:

```
random_word = r.get_random_word(hasDictionaryDef="true", includePartOfSpeech="noun,verb", minCorpusCount=1, maxCorpusCount=10, minDictionaryCount=1, maxDictionaryCount=10, minLength=5, maxLength=10)
```

**Comment by jared-bloomer** [comment]
Same Issue for me as well. Using a quick isolated script to test it out

The Script:
`#!/usr/bin/env python3

def word():
    from random_word import RandomWords
    r = RandomWords()
    word = r.get_random_word(hasDictionaryDef="true")
    return word

def main():
    print(word())

if __name__ == "__main__":
    main()`

The Result:
`Traceback (most recent call last):
  File "./randomword", line 13, in <module>
    main()
  File "./randomword", line 10, in main
    print(word())
  File "./randomword", line 6, in word
    word = r.get_random_word(hasDictionaryDef="true")
  File "/usr/local/lib/python3.7/site-packages/random_word/random_word.py", line 60, in get_random_word
    "Error occured, No result found. If you think this was a mistake than raise issue at {}".format(self.issue_url))
Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues`

**Comment by BBFCGaming** [comment]
I had the same problem while generating a few random words in a loop, but fixed it by importing time and adding `time.sleep(2)` in between. You might need to add kore to the 2 for a slower internet (idk how it really works) but thats how I fixed it

**Comment by BBFCGaming** [comment]
Same thing is happening to me. I tried to put `time.sleep(2)` in between the lines, but it didn't fix it.

**Comment by EdwardTheLegend** [comment]
I get the same thing too. My current solution is close it down and come back later.

**Comment by alliefitter** [comment]
I just got this error, though it doesn't seem to be persistent. I've resorted to using this function.
```
def make_random_word(self):
    words = RandomWords()
    word = None
    while not word:
        try:
            word = words.get_random_word()
        except:
            pass

    return word
```

**Comment by juan-solorio-program** [comment]
Same issue here. 

Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues

**Comment by vaibhavsingh97** [comment]
I had released a new version on PyPI (https://pypi.org/project/Random-Word/1.0.5/), this will fix recent issues.

**Comment by bhavingpt** [comment]
Hey, still running into this issue.
