### ISSUE TITLE
Test cases are not working

### ISSUE THREAD

**Issue by vaibhavsingh97** [vaibhavsingh97/random-word#3]
**Describe the bug**
There should be an automated test. Right now We have tests https://github.com/vaibhavsingh97/random-word/blob/master/random_word/tests/test_word.py but it's not working when we run `nosetests`

**To Reproduce**
1. open terminal and navigate to `random-word` repo
2. run `nosetests`
3. Shows run 0 tests

**Expected behavior**
Test should run as expected

**Screenshots**
![image](https://user-images.githubusercontent.com/8705386/42226660-23346654-7efd-11e8-9123-7d13afe582f9.png)

**Environment (please complete the following information):**
 - OS: `Darwin 16.7.0 Darwin Kernel Version 16.7.0: Fri Apr 27 17:59:46 PDT 2018; root:xnu-3789.73.13~1/RELEASE_X86_64 x86_64`
 - Python 3.7.0

**Additional context**
N/A

**Comment by jatin69** [comment]
Hey, I cannot work on the app with the config file. You'll need to lend it.

**Comment by igagankalra** [comment]
Hey, need a config file for the script to work.

**Comment by vaibhavsingh97** [comment]
Closing since it resolved in https://github.com/vaibhavsingh97/random-word/commit/37d579cc97fbaafa8e949fa7ecbdd1c731d309cf
