### ISSUE TITLE
get_random_word() function bug

### ISSUE THREAD

**Issue by Puhalenthi** [vaibhavsingh97/random-word#32]
The get_random_word() function is outputting the message: """Exception: Error occurred, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues"
It is not letting me create a random word. After multiple times of using the functions, it is printing errors

I was expecting it to return a random word without any errors.

OS- Windows 10
Python 3.8

**Comment by jackprogramsjp** [comment]
This is happening to me too.

**Comment by bdpedigo** [comment]
Same here

**Comment by JoelLefkowitz** [comment]
The Api is rejecting requests with the current key. 
Response: <Response [429]>
Result: {'message': 'API rate limit exceeded'}
#33 Should make issues like this easier to rectify once merged.

**Comment by matthewpugs** [comment]
ya recently I haven't been able to generate any words

**Comment by jackprogramsjp** [comment]
Guys, forget about this. The owner of random-word didn't update this for like 2 years. Just use https://raw.githubusercontent.com/sindresorhus/mnemonic-words/master/words.json to get random word.

```py
import json
import random
import urllib.request

url = urllib.request.urlopen("https://raw.githubusercontent.com/sindresorhus/mnemonic-words/master/words.json")
words = json.loads(url.read())
random_word = random.choice(words)
```

**Comment by Puhalenthi** [comment]
Thanks for the help!

**Comment by patrickbelding** [comment]
working in 2020


```
import json
import random
import requests

response = requests.get("http://raw.githubusercontent.com/sindresorhus/mnemonic-words/master/words.json")
data = response.json()
random_word = random.choice(data)
print(random_word)
```

**Comment by bytercode** [comment]
same

**Comment by juan-solorio-program** [comment]
Same here. The strange thing is that it worked fine a couple of days ago, but today it just stopped working at all:

Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues

**Comment by vaibhavsingh97** [comment]
Thanks for reporting will update the package today, duplicate of https://github.com/vaibhavsingh97/random-word/issues/44
