### ISSUE TITLE
get_random_words() returns error every time.

### ISSUE THREAD

**Issue by edubu2** [vaibhavsingh97/random-word#41]
**Describe the bug**
Keep getting unexpected Exception "Error occured, No result found...."

**To Reproduce**
``
>>> from random_word import RandomWords
>>> r = RandomWords()
>>> r.get_random_words()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ewilens/anaconda3/lib/python3.8/site-packages/random_word/random_word.py", line 111, in get_random_words
    raise Exception(
Exception: Error occured, No result found. If you think this was a mistake than raise issue at https://github.com/vaibhavsingh97/random-word/issues
``

**Expected behavior**
I expected a list of random words to be printed to stdout

**Screenshots**

**Environment (please complete the following information):**
 - MacOS 10.15.7 conda

**Comment by MaximilianKlein92** [comment]
I have the same Issue!

**Comment by chikko80** [comment]
same issue here!

**Comment by guisuzuki-ene** [comment]
same here

**Comment by DoronGanel** [comment]
same issue

**Comment by quizwammer** [comment]
Same here

**Comment by flextian** [comment]
This is because this library uses the Wordnik API with one common API key, and the API rate limit is being exceeded. To generate the words reliably you would need to get your own API key and edit the config.py file as stated in the readme: 

>Add API Key in `random_word` directory defining API Key in `config.py`. If you don't have an API key than request your API key [here](https://developer.wordnik.com)
>
>```sh
>API_KEY = "<API KEY>"
>```
>
>After that, install your package locally
>
>```sh
>$ pip install -e .
>```

Right now there doesn't seem to be an easier way to specify your own API key for this library.

**Comment by HawkBrave** [comment]
same here

**Comment by vaibhavsingh97** [comment]
Release new version: https://pypi.org/project/Random-Word/1.0.5/

The above issue will be fixed in 1.0.5 version
