### ISSUE TITLE
Error occured, No result found

### ISSUE THREAD

**Issue by code-talks-abhay** [vaibhavsingh97/random-word#44]
**Describe the bug**
When I used the .get_random_word(), it is throwing the error: Error occurred, No result found

**Comment by ValtokIsHere** [comment]
same

**Comment by vaibhavsingh97** [comment]
Thanks for reporting, I am working on it, will update the package today. I didn't know that this small project would blow up, as I made this because I wanted to use this in one of my projects at university

**Comment by vaibhavsingh97** [comment]
I had released new version on PYPI (https://pypi.org/project/Random-Word/1.0.5/), this will fix recent issues. Next weekend, I will refactor the whole repository to support multiple sources like Oxford, etc
