### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by vaibhavsingh97** [vaibhavsingh97/random-word#6]
**Expected Behaviour**
There should be instructions to prevent this error

**Actual Behaviour**
There are no instructions to add API key to the project and because of those new contributors who clone to project will receive `ImportError: cannot import name 'config'` error

**Context**
Add following lines in the `readme.md` under Basic Setup

To add API Key,  add `config.py` in `random_word` directory defining API Key
```python
API_KEY = "<API KEY>"
```

**Comment by igagankalra** [comment]
Updated the Readme and submitted a pull request for that. You can accept it and close this issue,
