### ISSUE TITLE
ModuleNotFoundError when installing 1.0.8 with pip

### ISSUE THREAD

**Issue by marko213** [vaibhavsingh97/random-word#81]
**Describe the bug**
Installing the package version 1.0.8 from PyPI does not generate the module directory, causing a `ModuleNotFoundError` even after installation.

**To Reproduce**

0. Remove any current installed version of `random-word`: `pip uninstall random-word`
1. Install the package via `pip`: `pip install random-word` (`pip install random-word==1.0.8`)
2. Try to import the module in python: `import random_word`

**Expected behavior**
The module should import correctly after installation.

**Environment:**
 - OS: Arch Linux
 - Python 3.10

**Additional context**
Noticed [on reddit](https://www.reddit.com/r/learnpython/comments/ux4mwe/). Current workaround is to install `random-word==1.0.7`.

The current build also seems to place `tests` and `utils`  under `site-packages`, possibly hinting to a wrong relative directory being used.

**Comment by vaibhavsingh97** [comment]
@marko213 Thanks for reporting will look into it.

**Comment by vaibhavsingh97** [comment]
Thanks for the reproducing steps. I will release a new version in a few days.

**Comment by vaibhavsingh97** [comment]
Fixed in v1.0.10
